-- AUTO-GENERATED BY CANONFLOW MIGRATION ENGINE
BEGIN;

CREATE TABLE public.products (
    product_id uuid NOT NULL PRIMARY KEY,
    name text NOT NULL,
    price numeric NOT NULL
);
ALTER TABLE public.orders ADD COLUMN discount numeric NOT NULL;
ALTER TABLE public.users ADD COLUMN status text NOT NULL;

COMMIT;
