module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module aircraftGenerators =
    let _dummy = ()
    let genmax_capacity = Gen.choose(1, 1000000)
    let arbmax_capacity = Arb.fromGen genmax_capacity

module bookingGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["HOLD"; "CONFIRMED"; "CANCELLED"]
    let arbstatus = Arb.fromGen genstatus

module crewGenerators =
    let _dummy = ()
    let genrole = Gen.elements ["PILOT"; "COPILOT"; "FLIGHT_ATTENDANT"; "PURSER"]
    let arbrole = Arb.fromGen genrole
    let genstatus = Gen.elements ["ACTIVE"; "REST"; "ON_LEAVE"]
    let arbstatus = Arb.fromGen genstatus

module flightGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["SCHEDULED"; "BOARDING"; "DEPARTED"; "ARRIVED"; "CANCELLED"]
    let arbstatus = Arb.fromGen genstatus

module flight_crewGenerators =
    let _dummy = ()

module loyaltyGenerators =
    let _dummy = ()
    let gentier = Gen.elements ["BLUE"; "SILVER"; "GOLD"; "PLATINUM"]
    let arbtier = Arb.fromGen gentier
    let genpoints = Gen.choose(0, 1000000)
    let arbpoints = Arb.fromGen genpoints

module passengerGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["ACTIVE"; "BANNED"]
    let arbstatus = Arb.fromGen genstatus

module paymentGenerators =
    let _dummy = ()
    let genamount = Gen.choose(1, 1000000)
    let arbamount = Arb.fromGen genamount
    let genstatus = Gen.elements ["PENDING"; "AUTHORIZED"; "CAPTURED"; "REFUNDED"; "FAILED"]
    let arbstatus = Arb.fromGen genstatus

module seatGenerators =
    let _dummy = ()
    let genclass = Gen.elements ["ECONOMY"; "PREMIUM"; "BUSINESS"; "FIRST"]
    let arbclass = Arb.fromGen genclass

module ticketGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["ISSUED"; "USED"; "VOID"]
    let arbstatus = Arb.fromGen genstatus

