module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module accountGenerators =
    let _dummy = ()
    let gencash_balance = Gen.choose(0, 1000000)
    let arbcash_balance = Arb.fromGen gencash_balance

module positionGenerators =
    let _dummy = ()
    let genshares = Gen.choose(0, 1000000)
    let arbshares = Arb.fromGen genshares

module trade_orderGenerators =
    let _dummy = ()
    let genside = Gen.elements ["BUY"; "SELL"]
    let arbside = Arb.fromGen genside
    let genquantity = Gen.choose(1, 1000000)
    let arbquantity = Arb.fromGen genquantity
    let genlimit_price = Gen.choose(1, 1000000)
    let arblimit_price = Arb.fromGen genlimit_price
    let genstatus = Gen.elements ["PENDING"; "FILLED"; "REJECTED"]
    let arbstatus = Arb.fromGen genstatus

