// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
export function validate_ledger_transactions_amount(value: any): boolean {
    return value.amount > 0;
}
// Fidelity: Exact
export function validate_ledger_transactions_direction(value: any): boolean {
    return ["CREDIT", "DEBIT"].includes(value.direction);
}
// Fidelity: Exact
export function validate_ledger_transactions_status(value: any): boolean {
    return ["CREATED", "PENDING", "COMPLETED", "FAILED", "REVERSED"].includes(value.status);
}
// Fidelity: Exact
export function validate_wallet_balances_available_balance(value: any): boolean {
    return value.available_balance >= 0;
}
// Fidelity: Exact
export function validate_wallet_balances_locked_balance(value: any): boolean {
    return value.locked_balance >= 0;
}
// Fidelity: Exact
export function validate_wallets_status(value: any): boolean {
    return ["ACTIVE", "SUSPENDED", "CLOSED"].includes(value.status);
}
