// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
export function validate_batches_level(value: any): boolean {
    return (value.level >= 1 && value.level <= 8);
}
// Fidelity: Exact
export function validate_batches_capacity(value: any): boolean {
    return (value.capacity > 0 && value.capacity <= 12);
}
// Fidelity: Exact
export function validate_batches_fee_monthly(value: any): boolean {
    return (value.fee_monthly >= 500 && value.fee_monthly <= 15000);
}
// Fidelity: Exact
export function validate_deposits_amount(value: any): boolean {
    return (value.amount >= 500 && value.amount >= 100);
}
// Fidelity: Exact
export function validate_deposits_opened_on(value: any): boolean {
    return value.maturity_date > value.opened_on;
}
// Fidelity: Exact
export function validate_deposits_maturity_date(value: any): boolean {
    return value.maturity_date > value.opened_on;
}
// Fidelity: Exact
export function validate_deposits_rate_pct(value: any): boolean {
    return (value.rate_pct >= 3.5 && value.rate_pct <= 9.25);
}
// Fidelity: Exact
export function validate_enrollments_discount_pct(value: any): boolean {
    return (value.discount_pct >= 0 && value.discount_pct <= 25);
}
// Fidelity: Exact
export function validate_exams_marks(value: any): boolean {
    return (value.marks >= 0 && value.marks <= 100);
}
// Fidelity: Unsupported
  "Cannot transpile raw SQL: (((theory_marks + practical_marks) <= 100))"
export function validate_exams_theory_marks(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported
  "Cannot transpile raw SQL: (((theory_marks + practical_marks) <= 100))"
export function validate_exams_practical_marks(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_guarantees_guarantor_share_pct(value: any): boolean {
    if (value === null || value === undefined) return true;
    return value.guarantor_share_pct >= 10;
}
// Fidelity: Exact
export function validate_gurus_years_experience(value: any): boolean {
    return value.years_experience > 0;
}
// Fidelity: Exact
export function validate_gurus_specialization(value: any): boolean {
    return ["vocal", "violin", "veena", "mridangam", "flute"].includes(value.specialization);
}
// Fidelity: Exact
export function validate_ledger_ledger_adjustment(value: any): boolean {
    return (value.ledger_adjustment >= -5000 && value.ledger_adjustment <= 5000);
}
// Fidelity: Exact
export function validate_ledger_method(value: any): boolean {
    return ["cash", "neft", "upi"].includes(value.method);
}
// Fidelity: Exact
export function validate_ledger_transactions_amount(value: any): boolean {
    return value.amount > 0;
}
// Fidelity: Exact
export function validate_ledger_transactions_direction(value: any): boolean {
    return ["CREDIT", "DEBIT"].includes(value.direction);
}
// Fidelity: Exact
export function validate_ledger_transactions_status(value: any): boolean {
    return ["CREATED", "PENDING", "COMPLETED", "FAILED", "REVERSED"].includes(value.status);
}
// Fidelity: Exact
export function validate_loans_principal(value: any): boolean {
    return (value.principal >= 1000 && value.principal <= 500000);
}
// Fidelity: Exact
export function validate_loans_tenure_months(value: any): boolean {
    return (value.tenure_months >= 3 && value.tenure_months <= 84);
}
// Fidelity: Exact
export function validate_loans_interest_pct(value: any): boolean {
    return ((value.interest_pct > 0 && value.interest_pct <= 24) && value.interest_pct <= 18);
}
// Fidelity: Unsupported "Cannot transpile raw SQL: ((length((phone)::text) = 10))"
export function validate_members_phone(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported "Cannot transpile raw SQL: guardian_member_id IS NOT NULL"
export function validate_members_age(value: any): boolean {
    return (value.age >= 21 || true /* opaque sql */);
}
// Fidelity: Unsupported "Cannot transpile raw SQL: guardian_member_id IS NOT NULL"
export function validate_members_guardian_member_id(value: any): boolean {
    if (value === null || value === undefined) return true;
    return (value.age >= 21 || true /* opaque sql */);
}
// Fidelity: Exact
export function validate_members_share_balance(value: any): boolean {
    return value.share_balance >= 100;
}
// Fidelity: Exact
export function validate_members_riskGrade(value: any): boolean {
    return (value."riskGrade" >= 'A' && value."riskGrade" <= 'E');
}
// Fidelity: Exact
export function validate_payments_amount(value: any): boolean {
    return value.amount > 0;
}
// Fidelity: Exact
export function validate_payments_method(value: any): boolean {
    return ["upi", "card", "cash"].includes(value.method);
}
// Fidelity: Exact
export function validate_scholarships_pct_waiver(value: any): boolean {
    return (value.pct_waiver > 0 && value.pct_waiver <= 100);
}
// Fidelity: Exact
export function validate_scholarships_min_attendance_pct(value: any): boolean {
    return (value.min_attendance_pct > 90 && value.min_attendance_pct < 75);
}
// Fidelity: Unsupported "Cannot transpile raw SQL: ((length((phone)::text) = 10))"
export function validate_students_phone(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_students_age(value: any): boolean {
    return (value.age >= 5 && value.age <= 90);
}
// Fidelity: Exact
export function validate_wallet_balances_available_balance(value: any): boolean {
    return value.available_balance >= 0;
}
// Fidelity: Exact
export function validate_wallet_balances_locked_balance(value: any): boolean {
    return value.locked_balance >= 0;
}
// Fidelity: Exact
export function validate_wallets_status(value: any): boolean {
    return ["ACTIVE", "SUSPENDED", "CLOSED"].includes(value.status);
}
