module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module bookingsGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["PENDING"; "ACCEPTED"; "IN_PROGRESS"; "COMPLETED"; "CANCELLED"]
    let arbstatus = Arb.fromGen genstatus
    let gentotal_amount = Gen.choose(0, 1000000)
    let arbtotal_amount = Arb.fromGen gentotal_amount

module professional_servicesGenerators =
    let _dummy = ()
    let genexperience_years = Gen.choose(0, 50)
    let arbexperience_years = Arb.fromGen genexperience_years

module servicesGenerators =
    let _dummy = ()
    let gencategory = Gen.elements ["CLEANING"; "PLUMBING"; "ELECTRICAL"; "SALON"; "APPLIANCE_REPAIR"]
    let arbcategory = Arb.fromGen gencategory
    let genbase_price = Gen.choose(0, 1000000)
    let arbbase_price = Arb.fromGen genbase_price

module usersGenerators =
    let _dummy = ()
    let genrole = Gen.elements ["CUSTOMER"; "PROFESSIONAL"]
    let arbrole = Arb.fromGen genrole
    let genstatus = Gen.elements ["ACTIVE"; "INACTIVE"; "BANNED"]
    let arbstatus = Arb.fromGen genstatus

