module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module billingGenerators =
    let _dummy = ()
    let gentotal_amount = Gen.choose(0, 1000000)
    let arbtotal_amount = Arb.fromGen gentotal_amount
    let genpatient_responsibility = Gen.choose(0, 1000000)
    let arbpatient_responsibility = Arb.fromGen genpatient_responsibility
    let geninsurance_responsibility = Gen.choose(0, 1000000)
    let arbinsurance_responsibility = Arb.fromGen geninsurance_responsibility
    let genstatus = Gen.elements ["DRAFT"; "PENDING_INSURANCE"; "PATIENT_DUE"; "PAID"; "OVERDUE"; "WRITTEN_OFF"]
    let arbstatus = Arb.fromGen genstatus

module claimsGenerators =
    let _dummy = ()
    let genclaimed_amount = Gen.choose(0, 1000000)
    let arbclaimed_amount = Arb.fromGen genclaimed_amount
    let genapproved_amount = Gen.choose(0, 1000000)
    let arbapproved_amount = Arb.fromGen genapproved_amount
    let genstatus = Gen.elements ["SUBMITTED"; "UNDER_REVIEW"; "APPROVED"; "PARTIAL_APPROVED"; "REJECTED"]
    let arbstatus = Arb.fromGen genstatus

module doctorGenerators =
    let _dummy = ()
    let genspecialty = Gen.elements ["GENERAL"; "CARDIOLOGY"; "NEUROLOGY"; "PEDIATRICS"; "ONCOLOGY"; "SURGERY"]
    let arbspecialty = Arb.fromGen genspecialty
    let genstatus = Gen.elements ["ACTIVE"; "ON_LEAVE"; "RETIRED"; "TERMINATED"]
    let arbstatus = Arb.fromGen genstatus

module insuranceGenerators =
    let _dummy = ()
    let gencoverage_limit = Gen.choose(0, 1000000)
    let arbcoverage_limit = Arb.fromGen gencoverage_limit
    let gencopay_percentage = Gen.choose(0, 100)
    let arbcopay_percentage = Arb.fromGen gencopay_percentage
    let genstatus = Gen.elements ["ACTIVE"; "EXPIRED"; "SUSPENDED"]
    let arbstatus = Arb.fromGen genstatus

module labGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["ORDERED"; "IN_PROGRESS"; "COMPLETED"; "CANCELLED"]
    let arbstatus = Arb.fromGen genstatus

module patientGenerators =
    let _dummy = ()
    let gengender = Gen.elements ["M"; "F"; "O"]
    let arbgender = Arb.fromGen gengender
    let genblood_group = Gen.elements ["A+"; "A-"; "B+"; "B-"; "O+"; "O-"; "AB+"; "AB-"]
    let arbblood_group = Arb.fromGen genblood_group
    let genstatus = Gen.elements ["REGISTERED"; "ADMITTED"; "DISCHARGED"; "DECEASED"]
    let arbstatus = Arb.fromGen genstatus

module pharmacyGenerators =
    let _dummy = ()
    let genquantity = Gen.choose(1, 1000000)
    let arbquantity = Arb.fromGen genquantity
    let genstatus = Gen.elements ["DISPENSED"; "REJECTED_INTERACTION"; "OUT_OF_STOCK"]
    let arbstatus = Arb.fromGen genstatus

module prescriptionGenerators =
    let _dummy = ()
    let genduration_days = Gen.choose(1, 365)
    let arbduration_days = Arb.fromGen genduration_days
    let genstatus = Gen.elements ["ACTIVE"; "FILLED"; "CANCELLED"; "EXPIRED"]
    let arbstatus = Arb.fromGen genstatus

module visitGenerators =
    let _dummy = ()
    let gentype = Gen.elements ["OUTPATIENT"; "INPATIENT"; "EMERGENCY"]
    let arbtype = Arb.fromGen gentype
    let genstatus = Gen.elements ["SCHEDULED"; "IN_PROGRESS"; "COMPLETED"; "CANCELLED"]
    let arbstatus = Arb.fromGen genstatus

