import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: ((form = ANY (ARRAY['Vocal'::text, 'Violin'::text, 'Veena'::text, 'Mridangam'::text, 'Flute'::text, 'Ensemble'::text])))
export const artists_formSchema = z.object({ form: z.enum(["Vocal", "Violin", "Veena", "Mridangam", "Flute", "Ensemble"]) });

export function validate_artists_form(value: any): boolean {
    return artists_formSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((standard_fee_band >= (0)::numeric))
export const artists_standard_fee_bandSchema = z.object({ standard_fee_band: z.number().gte(0) });

export function validate_artists_standard_fee_band(value: any): boolean {
    return artists_standard_fee_bandSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((quantity > 0))
export const bookings_quantitySchema = z.object({ quantity: z.number().gt(0) });

export function validate_bookings_quantity(value: any): boolean {
    return bookings_quantitySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((end_time > start_time))
export const kutcheris_start_timeSchema = z.any().refine(data => data.end_time > data.start_time);

export function validate_kutcheris_start_time(value: any): boolean {
    return kutcheris_start_timeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((end_time > start_time))
export const kutcheris_end_timeSchema = z.any().refine(data => data.end_time > data.start_time);

export function validate_kutcheris_end_time(value: any): boolean {
    return kutcheris_end_timeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['draft'::text, 'on-sale'::text, 'confirmed'::text, 'sold-out'::text, 'on-hold'::text, 'completed'::text, 'cancelled'::text])))
export const kutcheris_statusSchema = z.object({ status: z.enum(["draft", "on-sale", "confirmed", "sold-out", "on-hold", "completed", "cancelled"]) });

export function validate_kutcheris_status(value: any): boolean {
    return kutcheris_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((artist_fee >= (0)::numeric))
export const kutcheris_artist_feeSchema = z.object({ artist_fee: z.number().gte(0) });

export function validate_kutcheris_artist_fee(value: any): boolean {
    return kutcheris_artist_feeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((venue_cost >= (0)::numeric))
export const kutcheris_venue_costSchema = z.object({ venue_cost: z.number().gte(0) });

export function validate_kutcheris_venue_cost(value: any): boolean {
    return kutcheris_venue_costSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((price >= (0)::numeric))
export const ticket_tiers_priceSchema = z.object({ price: z.number().gte(0) });

export function validate_ticket_tiers_price(value: any): boolean {
    return ticket_tiers_priceSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((allocation >= 0)) AND ((sold_count <= allocation))
export const ticket_tiers_allocationSchema = z.object({ allocation: z.number().gte(0) }).and(z.any().refine(data => data.sold_count <= data.allocation));

export function validate_ticket_tiers_allocation(value: any): boolean {
    return ticket_tiers_allocationSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((sold_count <= allocation)) AND ((sold_count >= 0))
export const ticket_tiers_sold_countSchema = z.any().refine(data => data.sold_count <= data.allocation).and(z.object({ sold_count: z.number().gte(0) }));

export function validate_ticket_tiers_sold_count(value: any): boolean {
    return ticket_tiers_sold_countSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((seating_capacity > 0))
export const venues_seating_capacitySchema = z.object({ seating_capacity: z.number().gt(0) });

export function validate_venues_seating_capacity(value: any): boolean {
    return venues_seating_capacitySchema.safeParse(value).success;
}
