// AUTO-GENERATED BY CANONFLOW
// Fidelity: Unsupported: Cannot transpile raw SQL: ((form = ANY (ARRAY['Vocal'::text, 'Violin'::text, 'Veena'::text, 'Mridangam'::text, 'Flute'::text, 'Ensemble'::text])))
export function validate_artists_form(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_artists_standard_fee_band(value: any): boolean {
    return value.standard_fee_band >= 0;
}
// Fidelity: Exact
export function validate_bookings_quantity(value: any): boolean {
    return value.quantity > 0;
}
// Fidelity: Exact
export function validate_kutcheris_start_time(value: any): boolean {
    return value.end_time > value.start_time;
}
// Fidelity: Exact
export function validate_kutcheris_end_time(value: any): boolean {
    return value.end_time > value.start_time;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['draft'::text, 'on-sale'::text, 'confirmed'::text, 'sold-out'::text, 'on-hold'::text, 'completed'::text, 'cancelled'::text])))
export function validate_kutcheris_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_kutcheris_artist_fee(value: any): boolean {
    return value.artist_fee >= 0;
}
// Fidelity: Exact
export function validate_kutcheris_venue_cost(value: any): boolean {
    return value.venue_cost >= 0;
}
// Fidelity: Exact
export function validate_ticket_tiers_price(value: any): boolean {
    return value.price >= 0;
}
// Fidelity: Exact
export function validate_ticket_tiers_allocation(value: any): boolean {
    return (value.allocation >= 0 && value.sold_count <= value.allocation);
}
// Fidelity: Exact
export function validate_ticket_tiers_sold_count(value: any): boolean {
    return (value.sold_count <= value.allocation && value.sold_count >= 0);
}
// Fidelity: Exact
export function validate_venues_seating_capacity(value: any): boolean {
    return value.seating_capacity > 0;
}
