import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MODERATOR'::character varying, 'MEMBER'::character varying])::text[])))
export const group_members_roleSchema = z.object({ role: z.enum(["ADMIN", "MODERATOR", "MEMBER"]) });

export function validate_group_members_role(value: any): boolean {
    return group_members_roleSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((length((name)::text) >= 1) AND (length((name)::text) <= 100)))
export const groups_nameSchema = z.any();

export function validate_groups_name(value: any): boolean {
    return groups_nameSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL; Cannot transpile raw SQL; Cannot transpile raw SQL; Cannot transpile raw SQL

// Provenance: ((((receiver_id IS NOT NULL) AND (group_id IS NULL)) OR ((receiver_id IS NULL) AND (group_id IS NOT NULL))))
export const messages_receiver_idSchema = z.any().and(z.any()).or(z.any().and(z.any())).nullable();

export function validate_messages_receiver_id(value: any): boolean {
    return messages_receiver_idSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL; Cannot transpile raw SQL; Cannot transpile raw SQL; Cannot transpile raw SQL

// Provenance: ((((receiver_id IS NOT NULL) AND (group_id IS NULL)) OR ((receiver_id IS NULL) AND (group_id IS NOT NULL))))
export const messages_group_idSchema = z.any().and(z.any()).or(z.any().and(z.any())).nullable();

export function validate_messages_group_id(value: any): boolean {
    return messages_group_idSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((length(content) > 0) AND (length(content) <= 4000)))
export const messages_contentSchema = z.any();

export function validate_messages_content(value: any): boolean {
    return messages_contentSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((message_type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying, 'VIDEO'::character varying, 'AUDIO'::character varying, 'FILE'::character varying])::text[])))
export const messages_message_typeSchema = z.object({ message_type: z.enum(["TEXT", "IMAGE", "VIDEO", "AUDIO", "FILE"]) });

export function validate_messages_message_type(value: any): boolean {
    return messages_message_typeSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((read_at IS NULL) OR (read_at >= sent_at)))
export const messages_sent_atSchema = z.any().or(z.any().refine(data => data.read_at >= data.sent_at)).nullable();

export function validate_messages_sent_at(value: any): boolean {
    return messages_sent_atSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((read_at IS NULL) OR (read_at >= sent_at)))
export const messages_read_atSchema = z.any().or(z.any().refine(data => data.read_at >= data.sent_at)).nullable();

export function validate_messages_read_at(value: any): boolean {
    return messages_read_atSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((privacy_setting)::text = ANY ((ARRAY['EVERYONE'::character varying, 'CONTACTS'::character varying, 'NOBODY'::character varying])::text[])))
export const user_profiles_privacy_settingSchema = z.object({ privacy_setting: z.enum(["EVERYONE", "CONTACTS", "NOBODY"]) });

export function validate_user_profiles_privacy_setting(value: any): boolean {
    return user_profiles_privacy_settingSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL; Cannot transpile raw SQL

// Provenance: (((length((username)::text) >= 3) AND (length((username)::text) <= 50))) AND (((username)::text ~ '^[a-zA-Z0-9_]+$'::text))
export const users_usernameSchema = z.any().and(z.any());

export function validate_users_username(value: any): boolean {
    return users_usernameSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((length((phone_number)::text) >= 10) AND (length((phone_number)::text) <= 15)))
export const users_phone_numberSchema = z.any();

export function validate_users_phone_number(value: any): boolean {
    return users_phone_numberSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BANNED'::character varying, 'DELETED'::character varying])::text[])))
export const users_statusSchema = z.object({ status: z.enum(["ACTIVE", "INACTIVE", "BANNED", "DELETED"]) });

export function validate_users_status(value: any): boolean {
    return users_statusSchema.safeParse(value).success;
}
