module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module depositsGenerators =
    let _dummy = ()
    let _dummy = ()
    let genamount = Gen.choose(100, 1000000)
    let arbamount = Arb.fromGen genamount
    let genrate_pct = Gen.choose(3, 9)
    let arbrate_pct = Arb.fromGen genrate_pct

module guaranteesGenerators =
    let _dummy = ()
    let _dummy = ()
    let genguarantor_share_pct = Gen.choose(10, 1000000)
    let arbguarantor_share_pct = Arb.fromGen genguarantor_share_pct

module ledgerGenerators =
    let _dummy = ()
    let _dummy = ()
    let genledger_adjustment = Gen.choose(-5000, 5000)
    let arbledger_adjustment = Arb.fromGen genledger_adjustment
    let genmethod = Gen.elements ["cash"; "neft"; "upi"]
    let arbmethod = Arb.fromGen genmethod

module loansGenerators =
    let _dummy = ()
    let _dummy = ()
    let genprincipal = Gen.choose(1000, 750000)
    let arbprincipal = Arb.fromGen genprincipal
    let gentenure_months = Gen.choose(3, 84)
    let arbtenure_months = Arb.fromGen gentenure_months
    let geninterest_pct = Gen.choose(1, 18)
    let arbinterest_pct = Arb.fromGen geninterest_pct

module membersGenerators =
    let _dummy = ()
    let _dummy = ()
    let genshare_balance = Gen.choose(100, 1000000)
    let arbshare_balance = Arb.fromGen genshare_balance

