import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: ((total_amount >= (0)::numeric))
export const orders_total_amountSchema = z.object({ total_amount: z.number().gte(0) });

export function validate_orders_total_amount(value: any): boolean {
    return orders_total_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((discount >= (0)::numeric))
export const orders_discountSchema = z.object({ discount: z.number().gte(0) });

export function validate_orders_discount(value: any): boolean {
    return orders_discountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((price >= (0)::numeric))
export const products_priceSchema = z.object({ price: z.number().gte(0) });

export function validate_products_price(value: any): boolean {
    return products_priceSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'BANNED'::text])))
export const users_statusSchema = z.object({ status: z.enum(["ACTIVE", "BANNED"]) });

export function validate_users_status(value: any): boolean {
    return users_statusSchema.safeParse(value).success;
}
