import Foundation
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
func validate_ledger_transactions_amount(value: Any) -> Bool {
    return value.amount > Decimal(string: "0")!
}
// Fidelity: Exact
func validate_ledger_transactions_direction(value: Any) -> Bool {
    return Set(["CREDIT", "DEBIT"]).contains(value.direction)
}
// Fidelity: Exact
func validate_ledger_transactions_status(value: Any) -> Bool {
    return Set(["CREATED", "PENDING", "COMPLETED", "FAILED", "REVERSED"]).contains(value.status)
}
// Fidelity: Exact
func validate_wallet_balances_available_balance(value: Any) -> Bool {
    return value.available_balance >= Decimal(string: "0")!
}
// Fidelity: Exact
func validate_wallet_balances_locked_balance(value: Any) -> Bool {
    return value.locked_balance >= Decimal(string: "0")!
}
// Fidelity: Exact
func validate_wallets_status(value: Any) -> Bool {
    return Set(["ACTIVE", "SUSPENDED", "CLOSED"]).contains(value.status)
}
