import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
export const bookings_statusSchema = z.object({ status: z.enum(["PENDING", "ACCEPTED", "IN_PROGRESS", "COMPLETED", "CANCELLED"]) });

export function validate_bookings_status(value: any): boolean {
    return bookings_statusSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((completed_at IS NULL) OR (completed_at >= scheduled_time)))
export const bookings_scheduled_timeSchema = z.any().or(z.any().refine(data => data.completed_at >= data.scheduled_time));

export function validate_bookings_scheduled_time(value: any): boolean {
    return bookings_scheduled_timeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((total_amount >= 0.0))
export const bookings_total_amountSchema = z.object({ total_amount: z.number().gte(0.0) });

export function validate_bookings_total_amount(value: any): boolean {
    return bookings_total_amountSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((completed_at IS NULL) OR (completed_at >= scheduled_time)))
export const bookings_completed_atSchema = z.any().or(z.any().refine(data => data.completed_at >= data.scheduled_time)).nullable();

export function validate_bookings_completed_at(value: any): boolean {
    return bookings_completed_atSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((experience_years >= 0) AND (experience_years <= 50)))
export const professional_services_experience_yearsSchema = z.object({ experience_years: z.number().gte(0) }).and(z.object({ experience_years: z.number().lte(50) }));

export function validate_professional_services_experience_years(value: any): boolean {
    return professional_services_experience_yearsSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((category)::text = ANY ((ARRAY['CLEANING'::character varying, 'PLUMBING'::character varying, 'ELECTRICAL'::character varying, 'SALON'::character varying, 'APPLIANCE_REPAIR'::character varying])::text[])))
export const services_categorySchema = z.object({ category: z.enum(["CLEANING", "PLUMBING", "ELECTRICAL", "SALON", "APPLIANCE_REPAIR"]) });

export function validate_services_category(value: any): boolean {
    return services_categorySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((base_price >= 0.0))
export const services_base_priceSchema = z.object({ base_price: z.number().gte(0.0) });

export function validate_services_base_price(value: any): boolean {
    return services_base_priceSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'PROFESSIONAL'::character varying])::text[])))
export const users_roleSchema = z.object({ role: z.enum(["CUSTOMER", "PROFESSIONAL"]) });

export function validate_users_role(value: any): boolean {
    return users_roleSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((length((full_name)::text) >= 2) AND (length((full_name)::text) <= 100)))
export const users_full_nameSchema = z.any();

export function validate_users_full_name(value: any): boolean {
    return users_full_nameSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((length((phone_number)::text) >= 10) AND (length((phone_number)::text) <= 15)))
export const users_phone_numberSchema = z.any();

export function validate_users_phone_number(value: any): boolean {
    return users_phone_numberSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BANNED'::character varying])::text[])))
export const users_statusSchema = z.object({ status: z.enum(["ACTIVE", "INACTIVE", "BANNED"]) });

export function validate_users_status(value: any): boolean {
    return users_statusSchema.safeParse(value).success;
}
