// Four boundary probes — TS must agree with F# on all four verdicts.
const v = require('../client/validate.js'); // generated by canonflow contracts
const probes = [
  ['batches.fee_monthly', 499,  false], ['batches.fee_monthly', 15000, true],
  ['students.age',        4,    false], ['enrollments.discount_pct', 26, false],
];
let fail = 0;
for (const [field, value, expect] of probes) {
  const got = v.validate(field, value);
  console.log(`${field}(${value}) -> ${got} ${got===expect ? 'OK' : 'FAIL expected '+expect}`);
  if (got !== expect) fail++;
}
process.exit(fail);
