module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module customersGenerators =
    let genage = Gen.choose(18, 119)
    let arbage = Arb.fromGen genage
    let genstatus = Gen.elements ["ACTIVE"; "SUSPENDED"; "CLOSED"]
    let arbstatus = Arb.fromGen genstatus
    let gencredit_limit = Gen.choose(0, 1000000)
    let arbcredit_limit = Arb.fromGen gencredit_limit

module ordersGenerators =
    let genamount = Gen.choose(1, 1000000)
    let arbamount = Arb.fromGen genamount
    let gencurrency = Gen.elements ["INR"; "USD"; "EUR"]
    let arbcurrency = Arb.fromGen gencurrency
    let genorder_status = Gen.elements ["PLACED"; "PAID"; "CANCELLED"]
    let arborder_status = Arb.fromGen genorder_status

