version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: drill
      POSTGRES_PASSWORD: drill
      POSTGRES_DB: drill
    ports:
      - "5439:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
