// AUTO-GENERATED BY CANONFLOW
// Fidelity: Unsupported: Cannot transpile raw SQL: ((account_type = ANY (ARRAY['SAVINGS'::text, 'CURRENT'::text, 'LOAN'::text, 'FD'::text])))
export function validate_account_account_type(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['OPEN'::text, 'CLOSED'::text, 'FROZEN'::text])))
export function validate_account_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((screening_status = ANY (ARRAY['CLEARED'::text, 'FLAGGED'::text, 'UNDER_REVIEW'::text])))
export function validate_aml_screening_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])))
export function validate_audit_action(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(branch_code) = 4))
export function validate_branch_branch_code(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'CLOSED'::text, 'SUSPENDED'::text])))
export function validate_branch_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(card_number) >= 16))
export function validate_card_card_number(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((card_type = ANY (ARRAY['DEBIT'::text, 'CREDIT'::text, 'PREPAID'::text])))
export function validate_card_card_type(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'BLOCKED'::text, 'EXPIRED'::text])))
export function validate_card_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((charge_type = ANY (ARRAY['FEE'::text, 'TAX'::text, 'PENALTY'::text])))
export function validate_charges_charge_type(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_charges_amount(value: any): boolean {
    return value.amount > 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(currency_code) = 3))
export function validate_currency_currency_code(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(cif_number) = 8))
export function validate_customer_cif_number(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_customer_date_of_birth(value: any): boolean {
    return value.date_of_birth < value.CURRENT_DATE;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((risk_rating = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text])))
export function validate_customer_risk_rating(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'INACTIVE'::text, 'DORMANT'::text])))
export function validate_customer_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((role = ANY (ARRAY['TELLER'::text, 'MANAGER'::text, 'AUDITOR'::text, 'OFFICER'::text])))
export function validate_employee_role(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_exchange_rate_rate(value: any): boolean {
    return value.rate > 0;
}
// Fidelity: Exact
export function validate_fixed_deposit_principal(value: any): boolean {
    return value.principal > 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'MATURED'::text, 'BROKEN'::text])))
export function validate_fixed_deposit_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_interest_rate_rate_percentage(value: any): boolean {
    return (value.rate_percentage >= 0 && value.rate_percentage <= 100);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((document_type = ANY (ARRAY['PASSPORT'::text, 'NATIONAL_ID'::text, 'DRIVERS_LICENSE'::text])))
export function validate_kyc_document_type(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((entry_type = ANY (ARRAY['DR'::text, 'CR'::text])))
export function validate_ledger_entry_type(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_ledger_amount(value: any): boolean {
    return value.amount > 0;
}
// Fidelity: Exact
export function validate_limits_daily_transfer_limit(value: any): boolean {
    return value.daily_transfer_limit >= 0;
}
// Fidelity: Exact
export function validate_limits_overdraft_limit(value: any): boolean {
    return value.overdraft_limit >= 0;
}
// Fidelity: Exact
export function validate_loan_principal_amount(value: any): boolean {
    return value.principal_amount > 0;
}
// Fidelity: Exact
export function validate_loan_outstanding_balance(value: any): boolean {
    return value.outstanding_balance >= 0;
}
// Fidelity: Exact
export function validate_loan_interest_rate(value: any): boolean {
    return value.interest_rate >= 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['DISBURSED'::text, 'CLOSED'::text, 'DEFAULTED'::text])))
export function validate_loan_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_nominee_allocation_percentage(value: any): boolean {
    return (value.allocation_percentage > 0 && value.allocation_percentage <= 100);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((channel = ANY (ARRAY['SMS'::text, 'EMAIL'::text, 'PUSH'::text])))
export function validate_notifications_channel(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['PENDING'::text, 'SENT'::text, 'FAILED'::text])))
export function validate_notifications_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_statement_period_start(value: any): boolean {
    return value.period_end > value.period_start;
}
// Fidelity: Exact
export function validate_statement_period_end(value: any): boolean {
    return value.period_end > value.period_start;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((amount <> (0)::numeric))
export function validate_transaction_amount(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((txn_type = ANY (ARRAY['CREDIT'::text, 'DEBIT'::text])))
export function validate_transaction_txn_type(value: any): boolean {
    return true /* opaque sql */;
}
