import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: ((account_type = ANY (ARRAY['SAVINGS'::text, 'CURRENT'::text, 'LOAN'::text, 'FD'::text])))
export const account_account_typeSchema = z.object({ account_type: z.enum(["SAVINGS", "CURRENT", "LOAN", "FD"]) });

export function validate_account_account_type(value: any): boolean {
    return account_account_typeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['OPEN'::text, 'CLOSED'::text, 'FROZEN'::text])))
export const account_statusSchema = z.object({ status: z.enum(["OPEN", "CLOSED", "FROZEN"]) });

export function validate_account_status(value: any): boolean {
    return account_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((screening_status = ANY (ARRAY['CLEARED'::text, 'FLAGGED'::text, 'UNDER_REVIEW'::text])))
export const aml_screening_statusSchema = z.object({ screening_status: z.enum(["CLEARED", "FLAGGED", "UNDER_REVIEW"]) });

export function validate_aml_screening_status(value: any): boolean {
    return aml_screening_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])))
export const audit_actionSchema = z.object({ action: z.enum(["INSERT", "UPDATE", "DELETE"]) });

export function validate_audit_action(value: any): boolean {
    return audit_actionSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length(branch_code) = 4))
export const branch_branch_codeSchema = z.any();

export function validate_branch_branch_code(value: any): boolean {
    return branch_branch_codeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'CLOSED'::text, 'SUSPENDED'::text])))
export const branch_statusSchema = z.object({ status: z.enum(["ACTIVE", "CLOSED", "SUSPENDED"]) });

export function validate_branch_status(value: any): boolean {
    return branch_statusSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length(card_number) >= 16))
export const card_card_numberSchema = z.any();

export function validate_card_card_number(value: any): boolean {
    return card_card_numberSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((card_type = ANY (ARRAY['DEBIT'::text, 'CREDIT'::text, 'PREPAID'::text])))
export const card_card_typeSchema = z.object({ card_type: z.enum(["DEBIT", "CREDIT", "PREPAID"]) });

export function validate_card_card_type(value: any): boolean {
    return card_card_typeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'BLOCKED'::text, 'EXPIRED'::text])))
export const card_statusSchema = z.object({ status: z.enum(["ACTIVE", "BLOCKED", "EXPIRED"]) });

export function validate_card_status(value: any): boolean {
    return card_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((charge_type = ANY (ARRAY['FEE'::text, 'TAX'::text, 'PENALTY'::text])))
export const charges_charge_typeSchema = z.object({ charge_type: z.enum(["FEE", "TAX", "PENALTY"]) });

export function validate_charges_charge_type(value: any): boolean {
    return charges_charge_typeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((amount > (0)::numeric))
export const charges_amountSchema = z.object({ amount: z.number().gt(0) });

export function validate_charges_amount(value: any): boolean {
    return charges_amountSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length(currency_code) = 3))
export const currency_currency_codeSchema = z.any();

export function validate_currency_currency_code(value: any): boolean {
    return currency_currency_codeSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length(cif_number) = 8))
export const customer_cif_numberSchema = z.any();

export function validate_customer_cif_number(value: any): boolean {
    return customer_cif_numberSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((date_of_birth < CURRENT_DATE))
export const customer_date_of_birthSchema = z.any().refine(data => data.date_of_birth < data.CURRENT_DATE);

export function validate_customer_date_of_birth(value: any): boolean {
    return customer_date_of_birthSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((risk_rating = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text])))
export const customer_risk_ratingSchema = z.object({ risk_rating: z.enum(["LOW", "MEDIUM", "HIGH"]) });

export function validate_customer_risk_rating(value: any): boolean {
    return customer_risk_ratingSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'INACTIVE'::text, 'DORMANT'::text])))
export const customer_statusSchema = z.object({ status: z.enum(["ACTIVE", "INACTIVE", "DORMANT"]) });

export function validate_customer_status(value: any): boolean {
    return customer_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((role = ANY (ARRAY['TELLER'::text, 'MANAGER'::text, 'AUDITOR'::text, 'OFFICER'::text])))
export const employee_roleSchema = z.object({ role: z.enum(["TELLER", "MANAGER", "AUDITOR", "OFFICER"]) });

export function validate_employee_role(value: any): boolean {
    return employee_roleSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((rate > (0)::numeric))
export const exchange_rate_rateSchema = z.object({ rate: z.number().gt(0) });

export function validate_exchange_rate_rate(value: any): boolean {
    return exchange_rate_rateSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((principal > (0)::numeric))
export const fixed_deposit_principalSchema = z.object({ principal: z.number().gt(0) });

export function validate_fixed_deposit_principal(value: any): boolean {
    return fixed_deposit_principalSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'MATURED'::text, 'BROKEN'::text])))
export const fixed_deposit_statusSchema = z.object({ status: z.enum(["ACTIVE", "MATURED", "BROKEN"]) });

export function validate_fixed_deposit_status(value: any): boolean {
    return fixed_deposit_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((rate_percentage >= (0)::numeric) AND (rate_percentage <= (100)::numeric)))
export const interest_rate_rate_percentageSchema = z.object({ rate_percentage: z.number().gte(0) }).and(z.object({ rate_percentage: z.number().lte(100) }));

export function validate_interest_rate_rate_percentage(value: any): boolean {
    return interest_rate_rate_percentageSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((document_type = ANY (ARRAY['PASSPORT'::text, 'NATIONAL_ID'::text, 'DRIVERS_LICENSE'::text])))
export const kyc_document_typeSchema = z.object({ document_type: z.enum(["PASSPORT", "NATIONAL_ID", "DRIVERS_LICENSE"]) });

export function validate_kyc_document_type(value: any): boolean {
    return kyc_document_typeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((entry_type = ANY (ARRAY['DR'::text, 'CR'::text])))
export const ledger_entry_typeSchema = z.object({ entry_type: z.enum(["DR", "CR"]) });

export function validate_ledger_entry_type(value: any): boolean {
    return ledger_entry_typeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((amount > (0)::numeric))
export const ledger_amountSchema = z.object({ amount: z.number().gt(0) });

export function validate_ledger_amount(value: any): boolean {
    return ledger_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((daily_transfer_limit >= (0)::numeric))
export const limits_daily_transfer_limitSchema = z.object({ daily_transfer_limit: z.number().gte(0) });

export function validate_limits_daily_transfer_limit(value: any): boolean {
    return limits_daily_transfer_limitSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((overdraft_limit >= (0)::numeric))
export const limits_overdraft_limitSchema = z.object({ overdraft_limit: z.number().gte(0) });

export function validate_limits_overdraft_limit(value: any): boolean {
    return limits_overdraft_limitSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((principal_amount > (0)::numeric))
export const loan_principal_amountSchema = z.object({ principal_amount: z.number().gt(0) });

export function validate_loan_principal_amount(value: any): boolean {
    return loan_principal_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((outstanding_balance >= (0)::numeric))
export const loan_outstanding_balanceSchema = z.object({ outstanding_balance: z.number().gte(0) });

export function validate_loan_outstanding_balance(value: any): boolean {
    return loan_outstanding_balanceSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((interest_rate >= (0)::numeric))
export const loan_interest_rateSchema = z.object({ interest_rate: z.number().gte(0) });

export function validate_loan_interest_rate(value: any): boolean {
    return loan_interest_rateSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['DISBURSED'::text, 'CLOSED'::text, 'DEFAULTED'::text])))
export const loan_statusSchema = z.object({ status: z.enum(["DISBURSED", "CLOSED", "DEFAULTED"]) });

export function validate_loan_status(value: any): boolean {
    return loan_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((allocation_percentage > 0) AND (allocation_percentage <= 100)))
export const nominee_allocation_percentageSchema = z.object({ allocation_percentage: z.number().gt(0) }).and(z.object({ allocation_percentage: z.number().lte(100) }));

export function validate_nominee_allocation_percentage(value: any): boolean {
    return nominee_allocation_percentageSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((channel = ANY (ARRAY['SMS'::text, 'EMAIL'::text, 'PUSH'::text])))
export const notifications_channelSchema = z.object({ channel: z.enum(["SMS", "EMAIL", "PUSH"]) });

export function validate_notifications_channel(value: any): boolean {
    return notifications_channelSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['PENDING'::text, 'SENT'::text, 'FAILED'::text])))
export const notifications_statusSchema = z.object({ status: z.enum(["PENDING", "SENT", "FAILED"]) });

export function validate_notifications_status(value: any): boolean {
    return notifications_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((period_end > period_start))
export const statement_period_startSchema = z.any().refine(data => data.period_end > data.period_start);

export function validate_statement_period_start(value: any): boolean {
    return statement_period_startSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((period_end > period_start))
export const statement_period_endSchema = z.any().refine(data => data.period_end > data.period_start);

export function validate_statement_period_end(value: any): boolean {
    return statement_period_endSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((amount <> (0)::numeric))
export const transaction_amountSchema = z.any();

export function validate_transaction_amount(value: any): boolean {
    return transaction_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((txn_type = ANY (ARRAY['CREDIT'::text, 'DEBIT'::text])))
export const transaction_txn_typeSchema = z.object({ txn_type: z.enum(["CREDIT", "DEBIT"]) });

export function validate_transaction_txn_type(value: any): boolean {
    return transaction_txn_typeSchema.safeParse(value).success;
}
