// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
export function validate_customers_age(value: any): boolean {
    return (value.age >= 18 && value.age < 120);
}
// Fidelity: Exact
export function validate_customers_status(value: any): boolean {
    return ["ACTIVE", "SUSPENDED", "CLOSED"].includes(value.status);
}
// Fidelity: Exact
export function validate_customers_credit_limit(value: any): boolean {
    return (value.credit_limit >= 0 && value.credit_limit <= 1000000);
}
// Fidelity: Exact
export function validate_orders_amount(value: any): boolean {
    return value.amount > 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((currency = ANY (ARRAY['INR'::bpchar, 'USD'::bpchar, 'EUR'::bpchar])))
export function validate_orders_currency(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_orders_order_status(value: any): boolean {
    return ["PLACED", "PAID", "CANCELLED"].includes(value.order_status);
}
