version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wecar
    ports:
      - "5436:5432" # Use 5436 to avoid conflicts
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
