module CanonFlowRest.Api
open Giraffe
open Microsoft.AspNetCore.Http

// AUTO-GENERATED BY CANONFLOWREST
// These endpoints provide Noun-level CRUD backed by the DB boundaries.
// For complex workflows (Verbs), implement custom Handlers below.

let getaircraftHandler : HttpHandler = text "GET /aircraft - Not Implemented"
let postaircraftHandler : HttpHandler = text "POST /aircraft - Not Implemented"
let getbookingHandler : HttpHandler = text "GET /booking - Not Implemented"
let postbookingHandler : HttpHandler = text "POST /booking - Not Implemented"
let getcrewHandler : HttpHandler = text "GET /crew - Not Implemented"
let postcrewHandler : HttpHandler = text "POST /crew - Not Implemented"
let getflightHandler : HttpHandler = text "GET /flight - Not Implemented"
let postflightHandler : HttpHandler = text "POST /flight - Not Implemented"
let getflight_crewHandler : HttpHandler = text "GET /flight_crew - Not Implemented"
let postflight_crewHandler : HttpHandler = text "POST /flight_crew - Not Implemented"
let getloyaltyHandler : HttpHandler = text "GET /loyalty - Not Implemented"
let postloyaltyHandler : HttpHandler = text "POST /loyalty - Not Implemented"
let getpassengerHandler : HttpHandler = text "GET /passenger - Not Implemented"
let postpassengerHandler : HttpHandler = text "POST /passenger - Not Implemented"
let getpaymentHandler : HttpHandler = text "GET /payment - Not Implemented"
let postpaymentHandler : HttpHandler = text "POST /payment - Not Implemented"
let getseatHandler : HttpHandler = text "GET /seat - Not Implemented"
let postseatHandler : HttpHandler = text "POST /seat - Not Implemented"
let getticketHandler : HttpHandler = text "GET /ticket - Not Implemented"
let postticketHandler : HttpHandler = text "POST /ticket - Not Implemented"

let webApp =
    choose [
        route "/api/aircraft" >=> choose [
            GET >=> getaircraftHandler
            POST >=> postaircraftHandler
        ]
        route "/api/booking" >=> choose [
            GET >=> getbookingHandler
            POST >=> postbookingHandler
        ]
        route "/api/crew" >=> choose [
            GET >=> getcrewHandler
            POST >=> postcrewHandler
        ]
        route "/api/flight" >=> choose [
            GET >=> getflightHandler
            POST >=> postflightHandler
        ]
        route "/api/flight_crew" >=> choose [
            GET >=> getflight_crewHandler
            POST >=> postflight_crewHandler
        ]
        route "/api/loyalty" >=> choose [
            GET >=> getloyaltyHandler
            POST >=> postloyaltyHandler
        ]
        route "/api/passenger" >=> choose [
            GET >=> getpassengerHandler
            POST >=> postpassengerHandler
        ]
        route "/api/payment" >=> choose [
            GET >=> getpaymentHandler
            POST >=> postpaymentHandler
        ]
        route "/api/seat" >=> choose [
            GET >=> getseatHandler
            POST >=> postseatHandler
        ]
        route "/api/ticket" >=> choose [
            GET >=> getticketHandler
            POST >=> postticketHandler
        ]
        setStatusCode 404 >=> text "Not Found"
    ]
