// AUTO-GENERATED BY CANONFLOW
// Fidelity: Unsupported: Cannot transpile raw SQL: ((total_amount = (patient_responsibility + insurance_responsibility)))
export function validate_billing_total_amount(value: any): boolean {
    return (true /* opaque sql */ && value.total_amount >= 0);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((total_amount = (patient_responsibility + insurance_responsibility)))
export function validate_billing_patient_responsibility(value: any): boolean {
    return (value.patient_responsibility >= 0 && true /* opaque sql */);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((total_amount = (patient_responsibility + insurance_responsibility)))
export function validate_billing_insurance_responsibility(value: any): boolean {
    return (value.insurance_responsibility >= 0 && true /* opaque sql */);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['DRAFT'::text, 'PENDING_INSURANCE'::text, 'PATIENT_DUE'::text, 'PAID'::text, 'OVERDUE'::text, 'WRITTEN_OFF'::text])))
export function validate_billing_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_claims_claimed_amount(value: any): boolean {
    return ((value.approved_amount >= 0 && value.approved_amount <= value.claimed_amount) && value.claimed_amount > 0);
}
// Fidelity: Exact
export function validate_claims_approved_amount(value: any): boolean {
    if (value === null || value === undefined) return true;
    return (value.approved_amount >= 0 && value.approved_amount <= value.claimed_amount);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['SUBMITTED'::text, 'UNDER_REVIEW'::text, 'APPROVED'::text, 'PARTIAL_APPROVED'::text, 'REJECTED'::text])))
export function validate_claims_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((specialty = ANY (ARRAY['GENERAL'::text, 'CARDIOLOGY'::text, 'NEUROLOGY'::text, 'PEDIATRICS'::text, 'ONCOLOGY'::text, 'SURGERY'::text])))
export function validate_doctor_specialty(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'ON_LEAVE'::text, 'RETIRED'::text, 'TERMINATED'::text])))
export function validate_doctor_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_insurance_coverage_limit(value: any): boolean {
    return value.coverage_limit >= 0;
}
// Fidelity: Exact
export function validate_insurance_copay_percentage(value: any): boolean {
    return (value.copay_percentage >= 0 && value.copay_percentage <= 100);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'EXPIRED'::text, 'SUSPENDED'::text])))
export function validate_insurance_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: completed_time IS NULL
export function validate_lab_ordered_time(value: any): boolean {
    return (true /* opaque sql */ || value.completed_time >= value.ordered_time);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: completed_time IS NULL
export function validate_lab_completed_time(value: any): boolean {
    if (value === null || value === undefined) return true;
    return (true /* opaque sql */ || value.completed_time >= value.ordered_time);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ORDERED'::text, 'IN_PROGRESS'::text, 'COMPLETED'::text, 'CANCELLED'::text])))
export function validate_lab_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_patient_date_of_birth(value: any): boolean {
    return value.date_of_birth <= value.CURRENT_DATE;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((gender = ANY (ARRAY['M'::text, 'F'::text, 'O'::text])))
export function validate_patient_gender(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((blood_group = ANY (ARRAY['A+'::text, 'A-'::text, 'B+'::text, 'B-'::text, 'O+'::text, 'O-'::text, 'AB+'::text, 'AB-'::text])))
export function validate_patient_blood_group(value: any): boolean {
    if (value === null || value === undefined) return true;
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['REGISTERED'::text, 'ADMITTED'::text, 'DISCHARGED'::text, 'DECEASED'::text])))
export function validate_patient_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_pharmacy_quantity(value: any): boolean {
    return value.quantity > 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['DISPENSED'::text, 'REJECTED_INTERACTION'::text, 'OUT_OF_STOCK'::text])))
export function validate_pharmacy_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_prescription_duration_days(value: any): boolean {
    return (value.duration_days > 0 && value.duration_days <= 365);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'FILLED'::text, 'CANCELLED'::text, 'EXPIRED'::text])))
export function validate_prescription_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((type = ANY (ARRAY['OUTPATIENT'::text, 'INPATIENT'::text, 'EMERGENCY'::text])))
export function validate_visit_type(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['SCHEDULED'::text, 'IN_PROGRESS'::text, 'COMPLETED'::text, 'CANCELLED'::text])))
export function validate_visit_status(value: any): boolean {
    return true /* opaque sql */;
}
