import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((total_amount = (patient_responsibility + insurance_responsibility))) AND ((total_amount >= (0)::numeric))
export const billing_total_amountSchema = z.any().and(z.object({ total_amount: z.number().gte(0) }));

export function validate_billing_total_amount(value: any): boolean {
    return billing_total_amountSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((patient_responsibility >= (0)::numeric)) AND ((total_amount = (patient_responsibility + insurance_responsibility)))
export const billing_patient_responsibilitySchema = z.object({ patient_responsibility: z.number().gte(0) }).and(z.any());

export function validate_billing_patient_responsibility(value: any): boolean {
    return billing_patient_responsibilitySchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((insurance_responsibility >= (0)::numeric)) AND ((total_amount = (patient_responsibility + insurance_responsibility)))
export const billing_insurance_responsibilitySchema = z.object({ insurance_responsibility: z.number().gte(0) }).and(z.any());

export function validate_billing_insurance_responsibility(value: any): boolean {
    return billing_insurance_responsibilitySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['DRAFT'::text, 'PENDING_INSURANCE'::text, 'PATIENT_DUE'::text, 'PAID'::text, 'OVERDUE'::text, 'WRITTEN_OFF'::text])))
export const billing_statusSchema = z.object({ status: z.enum(["DRAFT", "PENDING_INSURANCE", "PATIENT_DUE", "PAID", "OVERDUE", "WRITTEN_OFF"]) });

export function validate_billing_status(value: any): boolean {
    return billing_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((approved_amount >= (0)::numeric) AND (approved_amount <= claimed_amount))) AND ((claimed_amount > (0)::numeric))
export const claims_claimed_amountSchema = z.object({ approved_amount: z.number().gte(0) }).and(z.any().refine(data => data.approved_amount <= data.claimed_amount)).and(z.object({ claimed_amount: z.number().gt(0) }));

export function validate_claims_claimed_amount(value: any): boolean {
    return claims_claimed_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((approved_amount >= (0)::numeric) AND (approved_amount <= claimed_amount)))
export const claims_approved_amountSchema = z.object({ approved_amount: z.number().gte(0) }).and(z.any().refine(data => data.approved_amount <= data.claimed_amount)).nullable();

export function validate_claims_approved_amount(value: any): boolean {
    return claims_approved_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['SUBMITTED'::text, 'UNDER_REVIEW'::text, 'APPROVED'::text, 'PARTIAL_APPROVED'::text, 'REJECTED'::text])))
export const claims_statusSchema = z.object({ status: z.enum(["SUBMITTED", "UNDER_REVIEW", "APPROVED", "PARTIAL_APPROVED", "REJECTED"]) });

export function validate_claims_status(value: any): boolean {
    return claims_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((specialty = ANY (ARRAY['GENERAL'::text, 'CARDIOLOGY'::text, 'NEUROLOGY'::text, 'PEDIATRICS'::text, 'ONCOLOGY'::text, 'SURGERY'::text])))
export const doctor_specialtySchema = z.object({ specialty: z.enum(["GENERAL", "CARDIOLOGY", "NEUROLOGY", "PEDIATRICS", "ONCOLOGY", "SURGERY"]) });

export function validate_doctor_specialty(value: any): boolean {
    return doctor_specialtySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'ON_LEAVE'::text, 'RETIRED'::text, 'TERMINATED'::text])))
export const doctor_statusSchema = z.object({ status: z.enum(["ACTIVE", "ON_LEAVE", "RETIRED", "TERMINATED"]) });

export function validate_doctor_status(value: any): boolean {
    return doctor_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((coverage_limit >= (0)::numeric))
export const insurance_coverage_limitSchema = z.object({ coverage_limit: z.number().gte(0) });

export function validate_insurance_coverage_limit(value: any): boolean {
    return insurance_coverage_limitSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((copay_percentage >= 0) AND (copay_percentage <= 100)))
export const insurance_copay_percentageSchema = z.object({ copay_percentage: z.number().gte(0) }).and(z.object({ copay_percentage: z.number().lte(100) }));

export function validate_insurance_copay_percentage(value: any): boolean {
    return insurance_copay_percentageSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'EXPIRED'::text, 'SUSPENDED'::text])))
export const insurance_statusSchema = z.object({ status: z.enum(["ACTIVE", "EXPIRED", "SUSPENDED"]) });

export function validate_insurance_status(value: any): boolean {
    return insurance_statusSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((completed_time IS NULL) OR (completed_time >= ordered_time)))
export const lab_ordered_timeSchema = z.any().or(z.any().refine(data => data.completed_time >= data.ordered_time));

export function validate_lab_ordered_time(value: any): boolean {
    return lab_ordered_timeSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((completed_time IS NULL) OR (completed_time >= ordered_time)))
export const lab_completed_timeSchema = z.any().or(z.any().refine(data => data.completed_time >= data.ordered_time)).nullable();

export function validate_lab_completed_time(value: any): boolean {
    return lab_completed_timeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ORDERED'::text, 'IN_PROGRESS'::text, 'COMPLETED'::text, 'CANCELLED'::text])))
export const lab_statusSchema = z.object({ status: z.enum(["ORDERED", "IN_PROGRESS", "COMPLETED", "CANCELLED"]) });

export function validate_lab_status(value: any): boolean {
    return lab_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((date_of_birth <= CURRENT_DATE))
export const patient_date_of_birthSchema = z.any().refine(data => data.date_of_birth <= data.CURRENT_DATE);

export function validate_patient_date_of_birth(value: any): boolean {
    return patient_date_of_birthSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((gender = ANY (ARRAY['M'::text, 'F'::text, 'O'::text])))
export const patient_genderSchema = z.object({ gender: z.enum(["M", "F", "O"]) });

export function validate_patient_gender(value: any): boolean {
    return patient_genderSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((blood_group = ANY (ARRAY['A+'::text, 'A-'::text, 'B+'::text, 'B-'::text, 'O+'::text, 'O-'::text, 'AB+'::text, 'AB-'::text])))
export const patient_blood_groupSchema = z.object({ blood_group: z.enum(["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"]) }).nullable();

export function validate_patient_blood_group(value: any): boolean {
    return patient_blood_groupSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['REGISTERED'::text, 'ADMITTED'::text, 'DISCHARGED'::text, 'DECEASED'::text])))
export const patient_statusSchema = z.object({ status: z.enum(["REGISTERED", "ADMITTED", "DISCHARGED", "DECEASED"]) });

export function validate_patient_status(value: any): boolean {
    return patient_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((quantity > 0))
export const pharmacy_quantitySchema = z.object({ quantity: z.number().gt(0) });

export function validate_pharmacy_quantity(value: any): boolean {
    return pharmacy_quantitySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['DISPENSED'::text, 'REJECTED_INTERACTION'::text, 'OUT_OF_STOCK'::text])))
export const pharmacy_statusSchema = z.object({ status: z.enum(["DISPENSED", "REJECTED_INTERACTION", "OUT_OF_STOCK"]) });

export function validate_pharmacy_status(value: any): boolean {
    return pharmacy_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((duration_days > 0) AND (duration_days <= 365)))
export const prescription_duration_daysSchema = z.object({ duration_days: z.number().gt(0) }).and(z.object({ duration_days: z.number().lte(365) }));

export function validate_prescription_duration_days(value: any): boolean {
    return prescription_duration_daysSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'FILLED'::text, 'CANCELLED'::text, 'EXPIRED'::text])))
export const prescription_statusSchema = z.object({ status: z.enum(["ACTIVE", "FILLED", "CANCELLED", "EXPIRED"]) });

export function validate_prescription_status(value: any): boolean {
    return prescription_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((type = ANY (ARRAY['OUTPATIENT'::text, 'INPATIENT'::text, 'EMERGENCY'::text])))
export const visit_typeSchema = z.object({ type: z.enum(["OUTPATIENT", "INPATIENT", "EMERGENCY"]) });

export function validate_visit_type(value: any): boolean {
    return visit_typeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['SCHEDULED'::text, 'IN_PROGRESS'::text, 'COMPLETED'::text, 'CANCELLED'::text])))
export const visit_statusSchema = z.object({ status: z.enum(["SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELLED"]) });

export function validate_visit_status(value: any): boolean {
    return visit_statusSchema.safeParse(value).success;
}
