import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: ((max_capacity > 0))
export const aircraft_max_capacitySchema = z.object({ max_capacity: z.number().gt(0) });

export function validate_aircraft_max_capacity(value: any): boolean {
    return aircraft_max_capacitySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['HOLD'::text, 'CONFIRMED'::text, 'CANCELLED'::text])))
export const booking_statusSchema = z.object({ status: z.enum(["HOLD", "CONFIRMED", "CANCELLED"]) });

export function validate_booking_status(value: any): boolean {
    return booking_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((role = ANY (ARRAY['PILOT'::text, 'COPILOT'::text, 'FLIGHT_ATTENDANT'::text, 'PURSER'::text])))
export const crew_roleSchema = z.object({ role: z.enum(["PILOT", "COPILOT", "FLIGHT_ATTENDANT", "PURSER"]) });

export function validate_crew_role(value: any): boolean {
    return crew_roleSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'REST'::text, 'ON_LEAVE'::text])))
export const crew_statusSchema = z.object({ status: z.enum(["ACTIVE", "REST", "ON_LEAVE"]) });

export function validate_crew_status(value: any): boolean {
    return crew_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((arrival_time > departure_time))
export const flight_departure_timeSchema = z.any().refine(data => data.arrival_time > data.departure_time);

export function validate_flight_departure_time(value: any): boolean {
    return flight_departure_timeSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((arrival_time > departure_time))
export const flight_arrival_timeSchema = z.any().refine(data => data.arrival_time > data.departure_time);

export function validate_flight_arrival_time(value: any): boolean {
    return flight_arrival_timeSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL; Cannot transpile raw SQL

// Provenance: ((length(origin) = 3)) AND ((origin <> destination))
export const flight_originSchema = z.any().and(z.any());

export function validate_flight_origin(value: any): boolean {
    return flight_originSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL; Cannot transpile raw SQL

// Provenance: ((length(destination) = 3)) AND ((origin <> destination))
export const flight_destinationSchema = z.any().and(z.any());

export function validate_flight_destination(value: any): boolean {
    return flight_destinationSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['SCHEDULED'::text, 'BOARDING'::text, 'DEPARTED'::text, 'ARRIVED'::text, 'CANCELLED'::text])))
export const flight_statusSchema = z.object({ status: z.enum(["SCHEDULED", "BOARDING", "DEPARTED", "ARRIVED", "CANCELLED"]) });

export function validate_flight_status(value: any): boolean {
    return flight_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((tier = ANY (ARRAY['BLUE'::text, 'SILVER'::text, 'GOLD'::text, 'PLATINUM'::text])))
export const loyalty_tierSchema = z.object({ tier: z.enum(["BLUE", "SILVER", "GOLD", "PLATINUM"]) });

export function validate_loyalty_tier(value: any): boolean {
    return loyalty_tierSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((points >= 0))
export const loyalty_pointsSchema = z.object({ points: z.number().gte(0) });

export function validate_loyalty_points(value: any): boolean {
    return loyalty_pointsSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((dob < CURRENT_DATE))
export const passenger_dobSchema = z.any().refine(data => data.dob < data.CURRENT_DATE);

export function validate_passenger_dob(value: any): boolean {
    return passenger_dobSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ACTIVE'::text, 'BANNED'::text])))
export const passenger_statusSchema = z.object({ status: z.enum(["ACTIVE", "BANNED"]) });

export function validate_passenger_status(value: any): boolean {
    return passenger_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((amount > (0)::numeric))
export const payment_amountSchema = z.object({ amount: z.number().gt(0) });

export function validate_payment_amount(value: any): boolean {
    return payment_amountSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length(currency) = 3))
export const payment_currencySchema = z.any();

export function validate_payment_currency(value: any): boolean {
    return payment_currencySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['PENDING'::text, 'AUTHORIZED'::text, 'CAPTURED'::text, 'REFUNDED'::text, 'FAILED'::text])))
export const payment_statusSchema = z.object({ status: z.enum(["PENDING", "AUTHORIZED", "CAPTURED", "REFUNDED", "FAILED"]) });

export function validate_payment_status(value: any): boolean {
    return payment_statusSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((class = ANY (ARRAY['ECONOMY'::text, 'PREMIUM'::text, 'BUSINESS'::text, 'FIRST'::text])))
export const seat_classSchema = z.object({ class: z.enum(["ECONOMY", "PREMIUM", "BUSINESS", "FIRST"]) });

export function validate_seat_class(value: any): boolean {
    return seat_classSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length(ticket_number) = 13))
export const ticket_ticket_numberSchema = z.any();

export function validate_ticket_ticket_number(value: any): boolean {
    return ticket_ticket_numberSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((status = ANY (ARRAY['ISSUED'::text, 'USED'::text, 'VOID'::text])))
export const ticket_statusSchema = z.object({ status: z.enum(["ISSUED", "USED", "VOID"]) });

export function validate_ticket_status(value: any): boolean {
    return ticket_statusSchema.safeParse(value).success;
}
