// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
export function validate_aircraft_max_capacity(value: any): boolean {
    return value.max_capacity > 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['HOLD'::text, 'CONFIRMED'::text, 'CANCELLED'::text])))
export function validate_booking_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((role = ANY (ARRAY['PILOT'::text, 'COPILOT'::text, 'FLIGHT_ATTENDANT'::text, 'PURSER'::text])))
export function validate_crew_role(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'REST'::text, 'ON_LEAVE'::text])))
export function validate_crew_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_flight_departure_time(value: any): boolean {
    return value.arrival_time > value.departure_time;
}
// Fidelity: Exact
export function validate_flight_arrival_time(value: any): boolean {
    return value.arrival_time > value.departure_time;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(origin) = 3)); Cannot transpile raw SQL: ((origin <> destination))
export function validate_flight_origin(value: any): boolean {
    return (true /* opaque sql */ && true /* opaque sql */);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(destination) = 3)); Cannot transpile raw SQL: ((origin <> destination))
export function validate_flight_destination(value: any): boolean {
    return (true /* opaque sql */ && true /* opaque sql */);
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['SCHEDULED'::text, 'BOARDING'::text, 'DEPARTED'::text, 'ARRIVED'::text, 'CANCELLED'::text])))
export function validate_flight_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((tier = ANY (ARRAY['BLUE'::text, 'SILVER'::text, 'GOLD'::text, 'PLATINUM'::text])))
export function validate_loyalty_tier(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_loyalty_points(value: any): boolean {
    return value.points >= 0;
}
// Fidelity: Exact
export function validate_passenger_dob(value: any): boolean {
    return value.dob < value.CURRENT_DATE;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ACTIVE'::text, 'BANNED'::text])))
export function validate_passenger_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_payment_amount(value: any): boolean {
    return value.amount > 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(currency) = 3))
export function validate_payment_currency(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['PENDING'::text, 'AUTHORIZED'::text, 'CAPTURED'::text, 'REFUNDED'::text, 'FAILED'::text])))
export function validate_payment_status(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((class = ANY (ARRAY['ECONOMY'::text, 'PREMIUM'::text, 'BUSINESS'::text, 'FIRST'::text])))
export function validate_seat_class(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((length(ticket_number) = 13))
export function validate_ticket_ticket_number(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['ISSUED'::text, 'USED'::text, 'VOID'::text])))
export function validate_ticket_status(value: any): boolean {
    return true /* opaque sql */;
}
