module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module ordersGenerators =
    let _dummy = ()
    let gentotal_amount = Gen.choose(0, 1000000)
    let arbtotal_amount = Arb.fromGen gentotal_amount
    let gendiscount = Gen.choose(0, 1000000)
    let arbdiscount = Arb.fromGen gendiscount

module productsGenerators =
    let _dummy = ()
    let genprice = Gen.choose(0, 1000000)
    let arbprice = Arb.fromGen genprice

module usersGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["ACTIVE"; "BANNED"]
    let arbstatus = Arb.fromGen genstatus

