module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module gatepassesGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["PENDING"; "APPROVED"; "DECLINED"; "ENTERED"; "EXITED"; "EXPIRED"]
    let arbstatus = Arb.fromGen genstatus

module residentsGenerators =
    let _dummy = ()

module visitorsGenerators =
    let _dummy = ()
    let genid_proof_type = Gen.elements ["AADHAAR"; "PAN"; "PASSPORT"; "DRIVING_LICENSE"; "OTHER"]
    let arbid_proof_type = Arb.fromGen genid_proof_type

