import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: ((amount >= (100)::numeric))
export const deposits_amountSchema = z.object({ amount: z.number().gte(100) });

export function validate_deposits_amount(value: any): boolean {
    return deposits_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((maturity_date > opened_on))
export const deposits_opened_onSchema = z.any().refine(data => data.maturity_date > data.opened_on);

export function validate_deposits_opened_on(value: any): boolean {
    return deposits_opened_onSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((maturity_date > opened_on))
export const deposits_maturity_dateSchema = z.any().refine(data => data.maturity_date > data.opened_on);

export function validate_deposits_maturity_date(value: any): boolean {
    return deposits_maturity_dateSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((rate_pct >= 3.5) AND (rate_pct <= 9.25)))
export const deposits_rate_pctSchema = z.object({ rate_pct: z.number().gte(3.5) }).and(z.object({ rate_pct: z.number().lte(9.25) }));

export function validate_deposits_rate_pct(value: any): boolean {
    return deposits_rate_pctSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((guarantor_share_pct >= (10)::numeric))
export const guarantees_guarantor_share_pctSchema = z.object({ guarantor_share_pct: z.number().gte(10) }).nullable();

export function validate_guarantees_guarantor_share_pct(value: any): boolean {
    return guarantees_guarantor_share_pctSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((ledger_adjustment >= ('-5000'::integer)::numeric) AND (ledger_adjustment <= (5000)::numeric)))
export const ledger_ledger_adjustmentSchema = z.object({ ledger_adjustment: z.number().gte(-5000) }).and(z.object({ ledger_adjustment: z.number().lte(5000) }));

export function validate_ledger_ledger_adjustment(value: any): boolean {
    return ledger_ledger_adjustmentSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((method)::text = ANY ((ARRAY['cash'::character varying, 'neft'::character varying, 'upi'::character varying])::text[])))
export const ledger_methodSchema = z.object({ method: z.enum(["cash", "neft", "upi"]) });

export function validate_ledger_method(value: any): boolean {
    return ledger_methodSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((principal >= (1000)::numeric) AND (principal <= (750000)::numeric)))
export const loans_principalSchema = z.object({ principal: z.number().gte(1000) }).and(z.object({ principal: z.number().lte(750000) }));

export function validate_loans_principal(value: any): boolean {
    return loans_principalSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((tenure_months >= 3) AND (tenure_months <= 84)))
export const loans_tenure_monthsSchema = z.object({ tenure_months: z.number().gte(3) }).and(z.object({ tenure_months: z.number().lte(84) }));

export function validate_loans_tenure_months(value: any): boolean {
    return loans_tenure_monthsSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((interest_pct <= (18)::numeric)) AND ((interest_pct <= (24)::numeric)) AND ((interest_pct > (0)::numeric))
export const loans_interest_pctSchema = z.object({ interest_pct: z.number().lte(18) }).and(z.object({ interest_pct: z.number().lte(24) })).and(z.object({ interest_pct: z.number().gt(0) }));

export function validate_loans_interest_pct(value: any): boolean {
    return loans_interest_pctSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length((phone)::text) = 10))
export const members_phoneSchema = z.any();

export function validate_members_phone(value: any): boolean {
    return members_phoneSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((age >= 21) OR (guardian_member_id IS NOT NULL)))
export const members_ageSchema = z.object({ age: z.number().gte(21) }).or(z.any());

export function validate_members_age(value: any): boolean {
    return members_ageSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((age >= 21) OR (guardian_member_id IS NOT NULL)))
export const members_guardian_member_idSchema = z.object({ age: z.number().gte(21) }).or(z.any()).nullable();

export function validate_members_guardian_member_id(value: any): boolean {
    return members_guardian_member_idSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((share_balance >= (100)::numeric))
export const members_share_balanceSchema = z.object({ share_balance: z.number().gte(100) });

export function validate_members_share_balance(value: any): boolean {
    return members_share_balanceSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((("riskGrade")::text >= 'A'::text) AND (("riskGrade")::text <= 'E'::text)))
export const members_riskGradeSchema = z.any();

export function validate_members_riskGrade(value: any): boolean {
    return members_riskGradeSchema.safeParse(value).success;
}
