module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module batchesGenerators =
    let _dummy = ()
    let genlevel = Gen.choose(1, 8)
    let arblevel = Arb.fromGen genlevel
    let gencapacity = Gen.choose(1, 12)
    let arbcapacity = Arb.fromGen gencapacity
    let genfee_monthly = Gen.choose(500, 20000)
    let arbfee_monthly = Arb.fromGen genfee_monthly

module enrollmentsGenerators =
    let _dummy = ()
    let gendiscount_pct = Gen.choose(0, 25)
    let arbdiscount_pct = Arb.fromGen gendiscount_pct

module examsGenerators =
    let _dummy = ()
    let genmarks = Gen.choose(0, 100)
    let arbmarks = Arb.fromGen genmarks

module gurusGenerators =
    let _dummy = ()
    let genyears_experience = Gen.choose(1, 1000000)
    let arbyears_experience = Arb.fromGen genyears_experience
    let genspecialization = Gen.elements ["vocal"; "violin"; "veena"; "mridangam"; "flute"]
    let arbspecialization = Arb.fromGen genspecialization

module paymentsGenerators =
    let _dummy = ()
    let genamount = Gen.choose(1, 1000000)
    let arbamount = Arb.fromGen genamount
    let genmethod = Gen.elements ["upi"; "card"; "cash"]
    let arbmethod = Arb.fromGen genmethod

module scholarshipsGenerators =
    let _dummy = ()
    let genpct_waiver = Gen.choose(1, 100)
    let arbpct_waiver = Arb.fromGen genpct_waiver

module studentsGenerators =
    let _dummy = ()
    let genage = Gen.choose(5, 90)
    let arbage = Arb.fromGen genage

