package com.layam.validators
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
fun validate_ledger_transactions_amount(value: dynamic): Boolean {
    return value.amount > java.math.BigDecimal("0")
}
// Fidelity: Exact
fun validate_ledger_transactions_direction(value: dynamic): Boolean {
    return setOf("CREDIT", "DEBIT").contains(value.direction)
}
// Fidelity: Exact
fun validate_ledger_transactions_status(value: dynamic): Boolean {
    return setOf("CREATED", "PENDING", "COMPLETED", "FAILED", "REVERSED").contains(value.status)
}
// Fidelity: Exact
fun validate_wallet_balances_available_balance(value: dynamic): Boolean {
    return value.available_balance >= java.math.BigDecimal("0")
}
// Fidelity: Exact
fun validate_wallet_balances_locked_balance(value: dynamic): Boolean {
    return value.locked_balance >= java.math.BigDecimal("0")
}
// Fidelity: Exact
fun validate_wallets_status(value: dynamic): Boolean {
    return setOf("ACTIVE", "SUSPENDED", "CLOSED").contains(value.status)
}
