import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'DECLINED'::character varying, 'ENTERED'::character varying, 'EXITED'::character varying, 'EXPIRED'::character varying])::text[])))
export const gatepasses_statusSchema = z.object({ status: z.enum(["PENDING", "APPROVED", "DECLINED", "ENTERED", "EXITED", "EXPIRED"]) });

export function validate_gatepasses_status(value: any): boolean {
    return gatepasses_statusSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((actual_arrival IS NULL) OR (actual_arrival >= (expected_arrival - '01:00:00'::interval))))
export const gatepasses_expected_arrivalSchema = z.any();

export function validate_gatepasses_expected_arrival(value: any): boolean {
    return gatepasses_expected_arrivalSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL; Cannot transpile raw SQL; Cannot transpile raw SQL

// Provenance: (((actual_arrival IS NULL) OR (actual_arrival >= (expected_arrival - '01:00:00'::interval)))) AND (((actual_departure IS NULL) OR ((actual_arrival IS NOT NULL) AND (actual_departure >= actual_arrival))))
export const gatepasses_actual_arrivalSchema = z.any().and(z.any().or(z.any().and(z.any().refine(data => data.actual_departure >= data.actual_arrival)))).nullable();

export function validate_gatepasses_actual_arrival(value: any): boolean {
    return gatepasses_actual_arrivalSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL; Cannot transpile raw SQL

// Provenance: (((actual_departure IS NULL) OR ((actual_arrival IS NOT NULL) AND (actual_departure >= actual_arrival))))
export const gatepasses_actual_departureSchema = z.any().or(z.any().and(z.any().refine(data => data.actual_departure >= data.actual_arrival))).nullable();

export function validate_gatepasses_actual_departure(value: any): boolean {
    return gatepasses_actual_departureSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length((unit_number)::text) > 0))
export const residents_unit_numberSchema = z.any();

export function validate_residents_unit_number(value: any): boolean {
    return residents_unit_numberSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((length((phone)::text) >= 10) AND (length((phone)::text) <= 15)))
export const residents_phoneSchema = z.any();

export function validate_residents_phone(value: any): boolean {
    return residents_phoneSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((length((phone)::text) >= 10) AND (length((phone)::text) <= 15)))
export const visitors_phoneSchema = z.any();

export function validate_visitors_phone(value: any): boolean {
    return visitors_phoneSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((id_proof_type)::text = ANY ((ARRAY['AADHAAR'::character varying, 'PAN'::character varying, 'PASSPORT'::character varying, 'DRIVING_LICENSE'::character varying, 'OTHER'::character varying])::text[])))
export const visitors_id_proof_typeSchema = z.object({ id_proof_type: z.enum(["AADHAAR", "PAN", "PASSPORT", "DRIVING_LICENSE", "OTHER"]) });

export function validate_visitors_id_proof_type(value: any): boolean {
    return visitors_id_proof_typeSchema.safeParse(value).success;
}
