module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module accountGenerators =
    let genaccount_type = Gen.elements ["SAVINGS"; "CURRENT"; "LOAN"; "FD"]
    let arbaccount_type = Arb.fromGen genaccount_type
    let genstatus = Gen.elements ["OPEN"; "CLOSED"; "FROZEN"]
    let arbstatus = Arb.fromGen genstatus

module amlGenerators =
    let genscreening_status = Gen.elements ["CLEARED"; "FLAGGED"; "UNDER_REVIEW"]
    let arbscreening_status = Arb.fromGen genscreening_status

module auditGenerators =
    let genaction = Gen.elements ["INSERT"; "UPDATE"; "DELETE"]
    let arbaction = Arb.fromGen genaction

module branchGenerators =
    let genstatus = Gen.elements ["ACTIVE"; "CLOSED"; "SUSPENDED"]
    let arbstatus = Arb.fromGen genstatus

module cardGenerators =
    let gencard_type = Gen.elements ["DEBIT"; "CREDIT"; "PREPAID"]
    let arbcard_type = Arb.fromGen gencard_type
    let genstatus = Gen.elements ["ACTIVE"; "BLOCKED"; "EXPIRED"]
    let arbstatus = Arb.fromGen genstatus

module chargesGenerators =
    let gencharge_type = Gen.elements ["FEE"; "TAX"; "PENALTY"]
    let arbcharge_type = Arb.fromGen gencharge_type
    let genamount = Gen.choose(1, 1000000)
    let arbamount = Arb.fromGen genamount

module currencyGenerators =
    let _dummy = ()

module customerGenerators =
    let genrisk_rating = Gen.elements ["LOW"; "MEDIUM"; "HIGH"]
    let arbrisk_rating = Arb.fromGen genrisk_rating
    let genstatus = Gen.elements ["ACTIVE"; "INACTIVE"; "DORMANT"]
    let arbstatus = Arb.fromGen genstatus

module employeeGenerators =
    let genrole = Gen.elements ["TELLER"; "MANAGER"; "AUDITOR"; "OFFICER"]
    let arbrole = Arb.fromGen genrole

module exchange_rateGenerators =
    let genrate = Gen.choose(1, 1000000)
    let arbrate = Arb.fromGen genrate

module fixed_depositGenerators =
    let genprincipal = Gen.choose(1, 1000000)
    let arbprincipal = Arb.fromGen genprincipal
    let genstatus = Gen.elements ["ACTIVE"; "MATURED"; "BROKEN"]
    let arbstatus = Arb.fromGen genstatus

module interest_rateGenerators =
    let genrate_percentage = Gen.choose(0, 100)
    let arbrate_percentage = Arb.fromGen genrate_percentage

module kycGenerators =
    let gendocument_type = Gen.elements ["PASSPORT"; "NATIONAL_ID"; "DRIVERS_LICENSE"]
    let arbdocument_type = Arb.fromGen gendocument_type

module ledgerGenerators =
    let genentry_type = Gen.elements ["DR"; "CR"]
    let arbentry_type = Arb.fromGen genentry_type
    let genamount = Gen.choose(1, 1000000)
    let arbamount = Arb.fromGen genamount

module limitsGenerators =
    let gendaily_transfer_limit = Gen.choose(0, 1000000)
    let arbdaily_transfer_limit = Arb.fromGen gendaily_transfer_limit
    let genoverdraft_limit = Gen.choose(0, 1000000)
    let arboverdraft_limit = Arb.fromGen genoverdraft_limit

module loanGenerators =
    let genprincipal_amount = Gen.choose(1, 1000000)
    let arbprincipal_amount = Arb.fromGen genprincipal_amount
    let genoutstanding_balance = Gen.choose(0, 1000000)
    let arboutstanding_balance = Arb.fromGen genoutstanding_balance
    let geninterest_rate = Gen.choose(0, 1000000)
    let arbinterest_rate = Arb.fromGen geninterest_rate
    let genstatus = Gen.elements ["DISBURSED"; "CLOSED"; "DEFAULTED"]
    let arbstatus = Arb.fromGen genstatus

module nomineeGenerators =
    let genallocation_percentage = Gen.choose(1, 100)
    let arballocation_percentage = Arb.fromGen genallocation_percentage

module notificationsGenerators =
    let genchannel = Gen.elements ["SMS"; "EMAIL"; "PUSH"]
    let arbchannel = Arb.fromGen genchannel
    let genstatus = Gen.elements ["PENDING"; "SENT"; "FAILED"]
    let arbstatus = Arb.fromGen genstatus

module statementGenerators =
    let _dummy = ()

module transactionGenerators =
    let gentxn_type = Gen.elements ["CREDIT"; "DEBIT"]
    let arbtxn_type = Arb.fromGen gentxn_type

