import { z } from "zod";
// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact

// Provenance: (((level >= 1) AND (level <= 8)))
export const batches_levelSchema = z.object({ level: z.number().gte(1) }).and(z.object({ level: z.number().lte(8) }));

export function validate_batches_level(value: any): boolean {
    return batches_levelSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((capacity > 0) AND (capacity <= 12)))
export const batches_capacitySchema = z.object({ capacity: z.number().gt(0) }).and(z.object({ capacity: z.number().lte(12) }));

export function validate_batches_capacity(value: any): boolean {
    return batches_capacitySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((fee_monthly >= (500)::numeric) AND (fee_monthly <= (20000)::numeric)))
export const batches_fee_monthlySchema = z.object({ fee_monthly: z.number().gte(500) }).and(z.object({ fee_monthly: z.number().lte(20000) }));

export function validate_batches_fee_monthly(value: any): boolean {
    return batches_fee_monthlySchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((discount_pct >= (0)::numeric) AND (discount_pct <= (25)::numeric)))
export const enrollments_discount_pctSchema = z.object({ discount_pct: z.number().gte(0) }).and(z.object({ discount_pct: z.number().lte(25) }));

export function validate_enrollments_discount_pct(value: any): boolean {
    return enrollments_discount_pctSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((marks >= 0) AND (marks <= 100)))
export const exams_marksSchema = z.object({ marks: z.number().gte(0) }).and(z.object({ marks: z.number().lte(100) }));

export function validate_exams_marks(value: any): boolean {
    return exams_marksSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((theory_marks + practical_marks) <= 100))
export const exams_theory_marksSchema = z.any();

export function validate_exams_theory_marks(value: any): boolean {
    return exams_theory_marksSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: (((theory_marks + practical_marks) <= 100))
export const exams_practical_marksSchema = z.any();

export function validate_exams_practical_marks(value: any): boolean {
    return exams_practical_marksSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((years_experience > 0))
export const gurus_years_experienceSchema = z.object({ years_experience: z.number().gt(0) });

export function validate_gurus_years_experience(value: any): boolean {
    return gurus_years_experienceSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((specialization)::text = ANY ((ARRAY['vocal'::character varying, 'violin'::character varying, 'veena'::character varying, 'mridangam'::character varying, 'flute'::character varying])::text[])))
export const gurus_specializationSchema = z.object({ specialization: z.enum(["vocal", "violin", "veena", "mridangam", "flute"]) });

export function validate_gurus_specialization(value: any): boolean {
    return gurus_specializationSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((amount > (0)::numeric))
export const payments_amountSchema = z.object({ amount: z.number().gt(0) });

export function validate_payments_amount(value: any): boolean {
    return payments_amountSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((method)::text = ANY ((ARRAY['upi'::character varying, 'card'::character varying, 'cash'::character varying])::text[])))
export const payments_methodSchema = z.object({ method: z.enum(["upi", "card", "cash"]) });

export function validate_payments_method(value: any): boolean {
    return payments_methodSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((pct_waiver > (0)::numeric) AND (pct_waiver <= (100)::numeric)))
export const scholarships_pct_waiverSchema = z.object({ pct_waiver: z.number().gt(0) }).and(z.object({ pct_waiver: z.number().lte(100) }));

export function validate_scholarships_pct_waiver(value: any): boolean {
    return scholarships_pct_waiverSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: ((min_attendance_pct < (75)::numeric)) AND ((min_attendance_pct > (90)::numeric))
export const scholarships_min_attendance_pctSchema = z.object({ min_attendance_pct: z.number().lt(75) }).and(z.object({ min_attendance_pct: z.number().gt(90) }));

export function validate_scholarships_min_attendance_pct(value: any): boolean {
    return scholarships_min_attendance_pctSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL

// Provenance: ((length((phone)::text) = 10))
export const students_phoneSchema = z.any();

export function validate_students_phone(value: any): boolean {
    return students_phoneSchema.safeParse(value).success;
}
// Fidelity: Exact

// Provenance: (((age >= 5) AND (age <= 90)))
export const students_ageSchema = z.object({ age: z.number().gte(5) }).and(z.object({ age: z.number().lte(90) }));

export function validate_students_age(value: any): boolean {
    return students_ageSchema.safeParse(value).success;
}
