module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module group_membersGenerators =
    let _dummy = ()
    let genrole = Gen.elements ["ADMIN"; "MODERATOR"; "MEMBER"]
    let arbrole = Arb.fromGen genrole

module groupsGenerators =
    let _dummy = ()

module messagesGenerators =
    let _dummy = ()
    let genmessage_type = Gen.elements ["TEXT"; "IMAGE"; "VIDEO"; "AUDIO"; "FILE"]
    let arbmessage_type = Arb.fromGen genmessage_type

module user_profilesGenerators =
    let _dummy = ()
    let genprivacy_setting = Gen.elements ["EVERYONE"; "CONTACTS"; "NOBODY"]
    let arbprivacy_setting = Arb.fromGen genprivacy_setting

module usersGenerators =
    let _dummy = ()
    let genstatus = Gen.elements ["ACTIVE"; "INACTIVE"; "BANNED"; "DELETED"]
    let arbstatus = Arb.fromGen genstatus

