module CanonFlow.FsCheck.Generators
open FsCheck
open System

// AUTO-GENERATED BY CANONFLOW
// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.

module artistsGenerators =
    let genform = Gen.elements ["Vocal"; "Violin"; "Veena"; "Mridangam"; "Flute"; "Ensemble"]
    let arbform = Arb.fromGen genform
    let genstandard_fee_band = Gen.choose(0, 1000000)
    let arbstandard_fee_band = Arb.fromGen genstandard_fee_band

module bookingsGenerators =
    let genquantity = Gen.choose(1, 1000000)
    let arbquantity = Arb.fromGen genquantity

module kutcherisGenerators =
    let genstatus = Gen.elements ["draft"; "on-sale"; "confirmed"; "sold-out"; "on-hold"; "completed"; "cancelled"]
    let arbstatus = Arb.fromGen genstatus
    let genartist_fee = Gen.choose(0, 1000000)
    let arbartist_fee = Arb.fromGen genartist_fee
    let genvenue_cost = Gen.choose(0, 1000000)
    let arbvenue_cost = Arb.fromGen genvenue_cost

module ticket_tiersGenerators =
    let genprice = Gen.choose(0, 1000000)
    let arbprice = Arb.fromGen genprice
    let genallocation = Gen.choose(0, 1000000)
    let arballocation = Arb.fromGen genallocation
    let gensold_count = Gen.choose(0, 1000000)
    let arbsold_count = Arb.fromGen gensold_count

module venuesGenerators =
    let genseating_capacity = Gen.choose(1, 1000000)
    let arbseating_capacity = Arb.fromGen genseating_capacity

