// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
export function validate_account_cash_balance(value: any): boolean {
    return value.cash_balance >= 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: (((length(ticker) >= 1) AND (length(ticker) <= 5)))
export function validate_position_ticker(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_position_shares(value: any): boolean {
    return value.shares >= 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: (((length(ticker) >= 1) AND (length(ticker) <= 5)))
export function validate_trade_order_ticker(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((side = ANY (ARRAY['BUY'::text, 'SELL'::text])))
export function validate_trade_order_side(value: any): boolean {
    return true /* opaque sql */;
}
// Fidelity: Exact
export function validate_trade_order_quantity(value: any): boolean {
    return value.quantity > 0;
}
// Fidelity: Exact
export function validate_trade_order_limit_price(value: any): boolean {
    return value.limit_price > 0;
}
// Fidelity: Unsupported: Cannot transpile raw SQL: ((status = ANY (ARRAY['PENDING'::text, 'FILLED'::text, 'REJECTED'::text])))
export function validate_trade_order_status(value: any): boolean {
    return true /* opaque sql */;
}
