// AUTO-GENERATED BY CANONFLOW
// Fidelity: Exact
import { z } from "zod";

// Provenance: ((cash_balance >= (0)::numeric))
export const account_cash_balanceSchema = z.object({ cash_balance: z.number().gte(0) });

export function validate_account_cash_balance(value: any): boolean {
    return account_cash_balanceSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL
import { z } from "zod";

// Provenance: (((length(ticker) >= 1) AND (length(ticker) <= 5)))
export const position_tickerSchema = z.any();

export function validate_position_ticker(value: any): boolean {
    return position_tickerSchema.safeParse(value).success;
}
// Fidelity: Exact
import { z } from "zod";

// Provenance: ((shares >= 0))
export const position_sharesSchema = z.object({ shares: z.number().gte(0) });

export function validate_position_shares(value: any): boolean {
    return position_sharesSchema.safeParse(value).success;
}
// Fidelity: Unsupported: Cannot transpile raw SQL
import { z } from "zod";

// Provenance: (((length(ticker) >= 1) AND (length(ticker) <= 5)))
export const trade_order_tickerSchema = z.any();

export function validate_trade_order_ticker(value: any): boolean {
    return trade_order_tickerSchema.safeParse(value).success;
}
// Fidelity: Exact
import { z } from "zod";

// Provenance: ((side = ANY (ARRAY['BUY'::text, 'SELL'::text])))
export const trade_order_sideSchema = z.object({ side: z.enum(["BUY", "SELL"]) });

export function validate_trade_order_side(value: any): boolean {
    return trade_order_sideSchema.safeParse(value).success;
}
// Fidelity: Exact
import { z } from "zod";

// Provenance: ((quantity > 0))
export const trade_order_quantitySchema = z.object({ quantity: z.number().gt(0) });

export function validate_trade_order_quantity(value: any): boolean {
    return trade_order_quantitySchema.safeParse(value).success;
}
// Fidelity: Exact
import { z } from "zod";

// Provenance: ((limit_price > (0)::numeric))
export const trade_order_limit_priceSchema = z.object({ limit_price: z.number().gt(0) });

export function validate_trade_order_limit_price(value: any): boolean {
    return trade_order_limit_priceSchema.safeParse(value).success;
}
// Fidelity: Exact
import { z } from "zod";

// Provenance: ((status = ANY (ARRAY['PENDING'::text, 'FILLED'::text, 'REJECTED'::text])))
export const trade_order_statusSchema = z.object({ status: z.enum(["PENDING", "FILLED", "REJECTED"]) });

export function validate_trade_order_status(value: any): boolean {
    return trade_order_statusSchema.safeParse(value).success;
}
